SUMMARY = "PHY configuration for a TI WiLink 8 Wi-Fi module"
DESCRIPTION = "\
The wl18xx driver reads ti-connectivity/wl18xx-conf.bin at probe and applies \
the front-end, antenna and TX power settings it carries. Without it the driver \
warns and falls back to built-in defaults. The file is generated by TI's wlconf \
from the INI file the module vendor supplies for its module."
HOMEPAGE = "https://git.ti.com/cgit/wilink8-wlan/18xx-ti-utils"

# The INI is the module vendor's data and is not carried here. To build the
# calibration, add it to SRC_URI and name it and its licence in a bbappend:
#
#   SRC_URI:append = " file://<module>.ini"
#   WL18XX_CONF_INI = "<module>.ini"
#   WL18XX_CONF_INI_LICENSE = "<licence of the INI>"
#
# and puts the package in the image from its configuration:
#
#   MACHINE_EXTRA_RRECOMMENDS:append:<machine> = " wl18xx-conf"
#
# Without an INI the recipe is skipped, so nothing may depend on it then.
WL18XX_CONF_INI ?= ""
WL18XX_CONF_INI_LICENSE ?= "CLOSED"

# wlconf is built and run on the build host; only its output is packaged. The
# output is TI's wl18xx-conf-default.bin with the INI's values laid over it, so
# it carries both licences.
LICENSE = "GPL-2.0-only & ${WL18XX_CONF_INI_LICENSE}"
LIC_FILES_CHKSUM = "file://wlconf/README;beginline=1;endline=21;md5=adc05a1903d3f107f85c90328e3a9438"

# R8.7_SP3. Configuration format 7.7, which is what wl18xx in this kernel reads.
SRCREV = "5040274cae5e88303e8a895c2707628fa72d58e8"
SRC_URI = " \
    git://git.ti.com/git/wilink8-wlan/18xx-ti-utils.git;protocol=https;branch=master \
    file://0001-wlconf-return-0-when-the-output-file-is-written.patch \
"

S = "${WORKDIR}/git"

PACKAGE_ARCH = "${MACHINE_ARCH}"

python () {
    if not d.getVar('WL18XX_CONF_INI'):
        raise bb.parse.SkipRecipe('WL18XX_CONF_INI is not set')
}

do_configure[noexec] = "1"

# wlconf opens struct.bin and dictionary.txt from the working directory.
do_compile() {
    oe_runmake -C ${S}/wlconf CC="${BUILD_CC}" CFLAGS="${BUILD_CFLAGS}" LDFLAGS="${BUILD_LDFLAGS}"
    cd ${S}/wlconf
    ./wlconf -i wl18xx-conf-default.bin -o ${B}/wl18xx-conf.bin -I ${WORKDIR}/${WL18XX_CONF_INI}
}

do_install() {
    install -d ${D}${nonarch_base_libdir}/firmware/ti-connectivity
    install -m 0644 ${B}/wl18xx-conf.bin \
        ${D}${nonarch_base_libdir}/firmware/ti-connectivity/wl18xx-conf.bin
}

FILES:${PN} = "${nonarch_base_libdir}/firmware/ti-connectivity/wl18xx-conf.bin"
